### ISSUE TITLE
Bundled LanguageTool does not have n-gram data

### ISSUE THREAD

**Issue by picsel2** [flathub/org.texstudio.TeXstudio#142]
The bundled LanguageTool does not make use of [n-gram data](https://dev.languagetool.org/finding-errors-using-n-gram-data.html).
These models are important to get most use of the tool but distributed separately from LanguageTool.

These n-gram datasets are really huge, so I think it would be best to keep these optional.
I suggest to add an extension point and pass its location to the `--languageModel` parameter startup.
Merging directories of the extension point would allow to have separate extensions for each language that still can be used simultaneously (e.g. I am only insterested in the English and German model).

**Comment by Alexander-Wilms** [comment]
Instead of maintaining extensions, I'd prefer to allow using the data via `--filesystem=host`. Since the user cannot change the `[command](https://github.com/flathub/org.texstudio.TeXstudio/blob/master/texstudio.sh#L21)` we use to start the `languagetool-server.jar`, we'd have to use a fixed path to either the data or a config file.

For that, `~/.var/app/org.texstudio.TeXstudio/` would probably be best. What do you think?

**Comment by picsel2** [comment]
Isn't `~/.var/app/org.texstudio.TeXstudio/` already accessible by default? That way the `--filesystem=host` permission would not be necessary.

Another thing is that I have a strong dislike for your solution. It requires the user to somehow find out where to download and unpack these files. I can't imagine a reasonable way to communicate this "hack".
Furthermore everyone has to keep those updated by hand which to me kind of contradicts the whole application distribution idea of flatpak.

What issues do you see with maintaining extensions?

**Comment by Alexander-Wilms** [comment]
`--filesystem=host` is already used because it is needed to compile documents which have not been saved yet, as well as `\include`d and ` \input`ed .tex files.


If you want to create the extensions, please go ahead. With `flatpak-external-data-checker`, they can be kept up-to-date automatically as well.

**Comment by picsel2** [comment]
I've created the manifest for German and English ngrams as proof of concept: 
 - https://github.com/picsel2/org.texstudio.TeXstudio.Extension.ngrams.de
 - https://github.com/picsel2/org.texstudio.TeXstudio.Extension.ngrams.en
(Building these will download several Gigabyte)

**Comment by Alexander-Wilms** [comment]
If it works for you locally, you can follow these steps:

https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app

**Comment by picsel2** [comment]
I opened PRs for en and de:
 - https://github.com/flathub/flathub/pull/4446
 - https://github.com/flathub/flathub/pull/4447

I'll follow with the remaining languages once the existing two are added to avoid the overhead of having to adapt _all_ PRs during the review. The manifests follow the same pattern, so this should be easy once the review of the first two is done.

**Comment by picsel2** [comment]
The extension point is already merged, so I view this as solved
