### ISSUE TITLE
Can't build anything out-of-the-box

### ISSUE THREAD

**Issue by Sjoerd1993** [flathub/org.texstudio.TeXstudio#161]
A clean install of TexStudio on Fedora Silverblue gives me the following error when trying to actually build a LaTeX document:

```
Could not start Build & View:PdfLaTeX:
flatpak-spawn --host pdflatex -synctex=1 -interaction=nonstopmode "beamersapienza".tex.
```
I'm currently installing TexLive seperately, but I recall this not being neccesary in the past and the `org.freedesktop.Sdk.Extension.texlive` extension coming with TeXStudio, is this no longer the case? Will update to see if that solves the issue, but either case it should work straight after a Flathub install.

**Comment by Alexander-Wilms** [comment]
I added `no-autodownload: true` some time ago: https://github.com/flathub/org.texstudio.TeXstudio/blob/b5a1ba6cf2f2ec47b2615c8e86a52886ba681f6e/org.texstudio.TeXstudio.yaml#L13

That way, one doesn't have to download TeX Live twice if one plans to use the distro packages.

You'll have to remove the `flatpak-spawn --host ` part of the commands under Options > Configure TeXstudio... > Commands.

I'll see if instead, I can specify a script for these commands by default, which would then decide on the fly whether to use the flatpak'd version of TeX Live or the version on the host.

**Comment by Sjoerd1993** [comment]
Thanks a lot for the reply, I did some further digging after my report here, and my initial conclusion from looking in the settings was that it was now set up to use the installed binaries (non-Flatpak). As I'm on Silverblue, that doesn't really work for me. I intended to update this issue, but as I need to get a presentation finished first I hadn't gotten around to that.

Either way, removing `flatpak-spawn --host` indeed works. I have `org.freedesktop.Sdk.Extension.texlive` installed, I assume it's a dependency to get it to work this way. Personally I preferred to have it "bundled" in the Flatpak even on a regular distro as Fedora Workstation as it keeps my base image clean from a million Texlive packages. Having that seperated is also part of the point behind Flatpak.

I'm just completely guessing here, as I never worked with add-ons. But perhaps it's possible to have TexLive available as optional add-on. So that it is a bit more visible, and people can just install it directly from e.g. GNOME Software.  Like Steam has for the Proton versions for instance: 

![image](https://github.com/flathub/org.texstudio.TeXstudio/assets/68477016/19ea459e-e68c-4944-bf92-a13853182cc9)

Combined with some way to automatically use the appropriate version (host or flatpak), that would make live a lot easier for people who want a Flatpak version that "just works". Already now in GNOME Software, the latest review is a one-star review of someone who had this same issue. It may not be obvious for all that texlive should be installed seperately, and then configuration needs to be changed to get it to work with Flatpak. But perhaps add-ons are a GNOME-Software thing, again I never really worked with such add-ons on the development-side of things. 

Either way, thanks a lot for the answer, your suggested solution worked great!

**Comment by Alexander-Wilms** [comment]
In order to have it listed, one would need to create an `org.texstudio.TeXstudio.TeXLive` image that contains the same data as `org.freedesktop.Sdk.Extension.texlive`.

And I think if I removed the `no-autodownload: true`, all users who prefer the distro packages would have to specify `--no-related` every time they install or update TeXstudio.

I can re-add the hint to the metainfo description that one has to install `org.texstudio.TeXstudio.TeXLive` manually.

**Comment by Alexander-Wilms** [comment]
@Sjoerd1993 Can you test build that will be available under https://github.com/flathub/org.texstudio.TeXstudio/pull/162 in a bit?

You'll need to delete `~/.var/app/org.texstudio.TeXstudio/`

**Comment by Alexander-Wilms** [comment]
@Sjoerd1993 I've now got the wrapper script working. That way, the same TeXstudio settings should work for both kinds of TeX Live distribution.

Can you delete or rename ~/.var/app/org.texstudio.TeXstudio and test the build which will be available under https://github.com/flathub/org.texstudio.TeXstudio/pull/162 in a bit?

**Comment by Sjoerd1993** [comment]
I tried build nr [60088](https://buildbot.flathub.org/#/builders/6/builds/60088), deleting `~/.var/app/org.texstudio.TeXstudio`. When I deleted `org.freedesktop.Sdk.Extension.texlive`, it gave me an expected error. When I reinstalled `org.freedesktop.Sdk.Extension.texlive`, it worked again just as it should.

So it seems to work as expected with the Flatpak TeXLive build at least.

**Comment by Alexander-Wilms** [comment]
Thanks. I also added an explanation to the metainfo file.

**Comment by JackGuyver** [comment]
I just found this issue, unfortunately *after* I spent quite some time of troubleshooting. So I thought I'd leave a comment here so that maybe others may find it via their search engine of choice.

Background:
TeXstudio installed via flatpak on a RHEL system
TeXlive installation on host that should be used

After updating my TeXstudio flatpak installation, all TeXlive executables stopped working:
```Error: Could not start the command: pdflatex -synctex=1 -interaction=nonstopmode "SomeFile".tex```
I tried adding the TeXlive directory to the PATH within the flatpak sandbox in different ways, without any notable effect.

Long story short, I now know that it is worth discussing about how to access host binaries and whether this is good practice, but when updating the tool, check your command preferences:
Options > Configure TeXstudio > Commands
each command using an executable on the host system should either use the **flatpak-wrapper** like this:
```flatpak-wrapper pdflatex -synctex=1 -interaction=nonstopmode %.tex```
or the built in method directly:
```flatpak-spawn --host pdflatex -synctex=1 -interaction=nonstopmode %.tex```

In a new installation the commands are replaced by [replace_commands.py](https://github.com/flathub/org.texstudio.TeXstudio/blob/master/replace_commands.py), if I understand it correctly. At least in my case, they were not changed during the update process.
