### ISSUE TITLE
epstopdf results in perl error

### ISSUE THREAD

**Issue by smiddy** [flathub/org.texstudio.TeXstudio#94]
Dear all,

I am using the flathub version of Texstudio for compiling my documents. Thanks for your work!

I face a problem with the conversion from eps to pdf. I issued a bug report with the texlive extension: flathub/org.freedesktop.Sdk.Extension.texlive#72

They asked me to discuss the matter with you as well. When I try to compile the MWE from the issue, I get the following error with Texstudio;
```
perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory system returned with code 32512
```

**Comment by nrbeaton** [comment]
I am getting the same issue when trying to use biber. Using bibtex instead works OK.

(I also commented on the texlive issue.)

**Comment by hknaack** [comment]
I also had the issue, that libperl.so cannot be found, when trying to make use of biblatex with biber.
My debugging results so far:

- getting a shell inside the sandbox: `flatpak run --command=sh org.texstudio.TeXstudio`
- running Perl, but it can't find libperl.so:
```
[org.texstudio.TeXstudio]$ perl
perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory
```
- Perl libraries are located in /app/texlive/lib/perl5, so set it in the library path: `[org.texstudio.TeXstudio]$ LD_LIBRARY_PATH=/app/texlive/lib/perl5/5.34.0/x86_64-linux/CORE/`
- now Perl is able to find its library and start:
```
[org.texstudio.TeXstudio]$ perl
print @INC
/usr/lib/sdk/texlive/lib/perl5/site_perl/5.34.0/x86_64-linux/usr/lib/sdk/texlive/lib/perl5/site_perl/5.34.0/usr/lib/sdk/texlive/lib/perl5/5.34.0/x86_64-linux/usr/lib/sdk/texlive/lib/perl5/5.34.0
```
- however Perl applications like biber need some Perl modules from the include path, which gets hardcoded into the variable `@INC` during compilation of Perl, so biber fails:
```
[org.texstudio.TeXstudio]$ biber
Can't locate strict.pm in @INC (you may need to install the strict module) (@INC contains: /usr/lib/sdk/texlive/lib/perl5/site_perl/5.34.0/x86_64-linux /usr/lib/sdk/texlive/lib/perl5/site_perl/5.34.0 /usr/lib/sdk/texlive/lib/perl5/5.34.0/x86_64-linux /usr/lib/sdk/texlive/lib/perl5/5.34.0) at /app/texlive/bin/biber line 4.
BEGIN failed--compilation aborted at /app/texlive/bin/biber line 4.
```

I'm totally unexperienced building Flatpaks, so someone more experienced needs to solve it. Maybe by locating the texlive sdk in /usr/lib/sdk/texlive instead of /app/texlive.

**Comment by Keksgesicht** [comment]
With the help of `find /app -name <file>` and the name of the file that was reported missing I found a workaround.
```
flatpak run --command=bash org.texstudio.TeXstudio

export PERL5LIB=/app/texlive/lib/perl5/site_perl/5.34.0/:/app/texlive/lib/perl5/5.34.0/
export LD_LIBRARY_PATH=/app/texlive/lib/:/app/texlive/lib/perl5/5.34.0/x86_64-linux/CORE/
biber
```
For permanent use apply this to your flatpak installation:
```
flatpak override --user --env=PERL5LIB=/app/texlive/lib/perl5/site_perl/5.34.0/:/app/texlive/lib/perl5/5.34.0/ org.texstudio.TeXstudio
flatpak override --user --env=LD_LIBRARY_PATH=/app/texlive/lib/:/app/texlive/lib/perl5/5.34.0/x86_64-linux/CORE/ org.texstudio.TeXstudio
```
So the files all exist, but the environment seems not be configured in the right way.

Even with the workaround compiling a LaTex source file does not seem to one click inside the flatpak.
Sometimes I still use (assuming main.tex):
```
flatpak run --command=biber org.texstudio.TeXstudio main
```

**Comment by hknaack** [comment]
@Keksgesicht Thanks, that fixed the issue for me. Even one-click compilation and view (F5) of my reference document (all temporary files deleted) runs through all the compile steps and finishes with a properly looking result.
The configuration option I changed for that is options > build (or compile? "Erzeugen") > change entry "standard bibliography" from Bibtex to Biber.
Does anybody want to start a pull request on this one? I may also give it a try.
